version: "3"
services:
  localstack:
    # Unable to upgrade beyond localstack 1.3 as it expects the AWS SDK V2
    image: localstack/localstack:1.3
    networks:
      - hmpps
    container_name: localstack-sqs-2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
