services:
  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
