version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8

jobs:
  validate:
    executor:
      name: hmpps/localstack
      jdk_tag: "16.0"
      localstack_tag: "0.12.9.1"
    steps:
      - checkout
      - run:
          name: Wait for SQS and SNS to be ready
          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4566
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_autoconfigure_test_results:
          path: hmpps-sqs-spring-boot-autoconfigure/build/test-results
      - store_autoconfigure_artifacts:
          path: hmpps-sqs-spring-boot-autoconfigure/build/reports/tests
      - store_test_results:
          path: test-app/build/test-results
      - store_artifacts:
          path: test-app/build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - hmpps-sqs-spring-boot-autoconfigure/build/libs
            - hmpps-sqs-spring-boot-starter/build/libs
            - build.gradle.kts

  publish:
    executor:
      name: hmpps/java
      tag: "16.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: |
            ORG_GRADLE_PROJECT_signingKey=$(echo -e "$ORG_GRADLE_PROJECT_signingKey")
            ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" hmpps-sqs-spring-boot-autoconfigure:publishToSonatype closeAndReleaseSonatypeStagingRepository
      - run:
          command: |
            ORG_GRADLE_PROJECT_signingKey=$(echo -e "$ORG_GRADLE_PROJECT_signingKey")
            ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" hmpps-sqs-spring-boot-starter:publishToSonatype closeAndReleaseSonatypeStagingRepository
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - build.gradle.kts

workflows:
  version: 2
  build-and-test:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - publish-approval:
          type: approval
          requires:
            - validate
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - publish-approval
          filters:
            branches:
              only:
                - main

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
