hmpps.sqs:
  provider: localstack
  queues:
    inboundqueue:
      queueName: inbound-queue
      dlqName: inbound-dlq
      subscribeTopicId: inboundtopic
      subscribeFilter: '{"eventType":[ "OFFENDER_MOVEMENT-RECEPTION", "OFFENDER_MOVEMENT-DISCHARGE"] }'
    outboundqueue:
      queueName: outbound-queue
      dlqName: outbound-dlq
      subscribeTopicId: outboundtopic
      subscribeFilter: '{"eventType":[ "offender.movement.reception"] }'
  topics:
    inboundtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:inbound-topic
    outboundtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:outbond-topic
