---
generic-service:
  nameOverride: hmpps-template-kotlin

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-template-kotlin
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-template-kotlin-cert
    path: /

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-template-kotlin:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    main-queue-sqs-instance-output:
      HMPPS_SQS_QUEUES_MAINQUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_MAINQUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_MAINQUEUE_QUEUE_NAME: "mainQueue"
    main-queue-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_MAINQUEUE_DLQ_ACCESS_KEY_ID: "dlq_access_key_id"
      HMPPS_SQS_QUEUES_MAINQUEUE_DLQ_SECRET_ACCESS_KEY: "dlq_secret_access_key"
      HMPPS_SQS_QUEUES_MAINQUEUE_DLQ_NAME: "mainDlq"
    another-queue-sqs-instance-output:
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_ACCESS_KEY_ID: "another_access_key_id"
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_SECRET_ACCESS_KEY: "another_secret_access_key"
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_QUEUE_NAME: "anotherQueue"
    another-queue-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_DLQ_ACCESS_KEY_ID: "dlq_another_access_key_id"
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_DLQ_SECRET_ACCESS_KEY: "dlq_another_secret_access_key"
      HMPPS_SQS_QUEUES_ANOTHERQUEUE_DLQ_NAME: "anotherDlq"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-template-kotlin
