name: Publish
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
permissions:
  contents: read
jobs:
  gradle-publish:
    name: Publish the gradle library
    runs-on: ubuntu-latest
    environment: 'publish'
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
      - name: Publish the plugin
        env:
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        shell: bash
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
