name: Publish
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
      gradle-command:
        type: string
        default: './gradlew check'
        required: false
permissions:
  contents: read
jobs:
  gradle-verify:
    name: Verify the gradle app
    runs-on: ubuntu-latest
    environment: 'publish'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish the plugin
        shell: bash
        run: |
          ORG_GRADLE_PROJECT_signingKey=$(echo "${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}")
          ORG_GRADLE_PROJECT_signingPassword=$(echo "${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}")
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
